---
- hosts: samplehost
  user: admuser
  sudo: yes
  tasks:
    - name: Setup rpm
      yum: name=http://dev.mysql.com/get/mysql57-community-release-el6-7.noarch.rpm
    - name: Install mysql client
      yum: name={{item}}
      with_items:
        - mysql-community-common.x86_64
        - mysql-community-client.x86_64
        - mysql-community-libs.x86_64
