---
- hosts: samplehost
  user: admuser
  sudo: yes
  tasks:
    - name: Install epel
      yum: name="http://ftp.iij.ad.jp/pub/linux/fedora/epel/6/x86_64/epel-release-6-8.noarch.rpm"
    - name: Install remi
      yum: name="http://rpms.famillecollet.com/enterprise/remi-release-6.rpm"
    - name: yum install php72
      yum: name={{item}} enablerepo=remi-php72 state=latest
      with_items:
        - php72
        - php72-php-common
        - php72-php-pdo
        - php72-php-cli
        - php72-php-devel
        - php72-php-gd
        - php72-php-mbstring
        - php72-php-mysqlnd
        - php72-php-bcmath
        - php72-php-xml
        - php72-php-json
        - php72-php-pecl-imagick
        - php72-php-pecl-imagick-devel
        - php72-php-pecl-mcrypt
        - php72-php-pecl-zip
